<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add Author' => 'Добавить автора',
    'Add Book' => 'Добавить книгу',
    'Add User' => 'Добавить пользователя',
    'Authors List' => 'Список авторов',
    'Books List' => 'Список книг',
    'Core' => 'Основное',
    'Dashboard' => 'Панель управления',
    'Data' => 'Данные',
    'Enter your password' => 'Введите Ваш пароль',
    'Enter your username' => 'Введите ваш логин',
    'Login' => 'Вход',
    'LoginButton' => 'Войти',
    'Logout' => 'Выход',
    'My Application' => 'Книжный каталог',
    'Password' => 'Пароль',
    'Please fill out the following fields to login:' => 'Пожалуйста, заполните все поля для входа:',
    'Remember Me' => 'Запомнить меня',
    'Report about top 10 authors' => 'Отчёт топ 10 авторов',
    'Username' => 'Никнейм',
    'Users List' => 'Список пользователей',
    'username' => 'Логин',
    'Book.JAVIDAN' => '',
    'Return to Dashboard' => 'Вернуться в панель управления',
    'Welcome to admin panel' => '',
    'Translatable String' => '@@@@',
    'users' => '@@Пользователи@@',
];
