<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'LoginButton' => 'Login',
    'Add Author' => '',
    'Add Book' => '',
    'Add User' => '',
    'Authors List' => '',
    'Book.JAVIDAN' => '',
    'Books List' => '',
    'Core' => '',
    'Dashboard' => '',
    'Data' => '',
    'Enter your password' => '',
    'Enter your username' => '',
    'Login' => '',
    'Logout' => '',
    'My Application' => '',
    'Password' => '',
    'Please fill out the following fields to login:' => '',
    'Remember Me' => '',
    'Report about top 10 authors' => '',
    'Return to Dashboard' => '',
    'Username' => '',
    'Users List' => '',
    'Welcome to admin panel' => '',
    'username' => '',
    'Translatable String' => '@@@@',
    'users' => '@@@@',
];
